{
    "name": "SO Projekt",
    "version": "14.0.1.3",
    "depends": ["sale_management", "payment", "website_sale"],
    "data": [
        "data/so_projekt_data.xml",
        "report/report_templates.xml",
        "data/report_layout.xml",
        "data/report_paperformat_data.xml",
        "views/layouts.xml",
        "views/res_config_settings_views.xml",
        "views/assets.xml",
        "views/templates.xml",
        "views/sale_views.xml",
        "views/res_partner_views.xml",
        "views/res_company_views.xml",
        "views/account_report_invoice_views.xml",
    ],
    "installable": True,
}
